<a href="https://colab.research.google.com/github/uthara999/Machine-Learning-Lab/blob/main/Numpy_workout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [7]:
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ar)
print(ar.shape)
print(ar.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
2


In [9]:
#slicing
print(ar[0,1])

2


In [13]:
print(ar[0:2,1])

[2 7]


In [20]:
arr=np.array([1.8,2.3,3.7,4.8,5.1])
newar=arr.astype("i")
print(newar)
print(newar.dtype)

[1 2 3 4 5]
int32


In [25]:
ar=np.array([1,2,3,4,5])
x=ar.copy()
ar[0]=42
print(ar)
#x=ar.copy()
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [24]:
ar=np.array([1,2,3,4,5])
x=ar.view()
ar[0]=42
print(ar)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [28]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=ar.reshape(4,3)
print(newar)
print(newar.shape)
print(newar.ndim)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2


In [29]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newar=ar.reshape(2,3,2)
print(newar)
print(newar.shape)
print(newar.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


In [30]:
ar=np.array([[1,2,3],[4,5,6]])
newar=ar.reshape(-1)
print(newar)
print(newar.shape)
print(newar.ndim)

[1 2 3 4 5 6]
(6,)
1


In [31]:
ar=np.array([1,2,3,4,5])
for x in ar:
    print(x)

1
2
3
4
5


In [33]:
ar=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#for x in ar:
    #print(x)
for x in ar:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8
9
10


In [40]:
ar=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
newar=np.array_split(ar,3)
print(newar)
print(newar[0])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]])]
[[1 2]
 [3 4]]


In [42]:
ar=np.array(['banana','apple','cherry'])
print(np.sort(ar))

['apple' 'banana' 'cherry']


In [44]:
from numpy import random
x=random.randint(100,size=(3,5))
print(x)

[[16 60 73  0 84]
 [30 66 78 55  5]
 [47 60  7 40 15]]
