<a href="https://colab.research.google.com/github/uthara999/Machine-Learning-Lab/blob/main/Numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Create a NumPy array with values ranging from 1 to 10. Perform element-wise multiplication by 2 and calculate the mean of the resulting array

In [ ]:
import numpy as np

original_array = np.arange(1, 11)

result_array = original_array * 2

mean_result = np.mean(result_array)

print("Original Array:", original_array)
print("Result Array after element-wise multiplication by 2:", result_array)
print("Mean of the Result Array:", mean_result)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Result Array after element-wise multiplication by 2: [ 2  4  6  8 10 12 14 16 18 20]
Mean of the Result Array: 11.0


In [ ]:
import numpy as np

# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Access the second column using slicing
second_column = array_2d[:, 1]

# Access the last row using slicing
last_row = array_2d[-1, :]

print("Original 2D Array:")
print(array_2d)

print("\nSecond Column:")
print(second_column)

print("\nLast Row:")
print(last_row)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second Column:
[2 5 8]

Last Row:
[7 8 9]


In [ ]:
import numpy as np

# Create two 1D NumPy arrays
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

# Concatenate horizontally
horizontal_concatenation = np.concatenate((array1, array2))

# Concatenate vertically
vertical_concatenation = np.concatenate((array1, array2), axis=0)

# Reshape the resulting array into a 2x4 matrix
reshaped_matrix = vertical_concatenation.reshape(2, 4)

print("Array 1:", array1)
print("Array 2:", array2)

print("\nHorizontally Concatenated Array:")
print(horizontal_concatenation)

print("\nVertically Concatenated Array:")
print(vertical_concatenation)

print("\nReshaped 2x4 Matrix:")
print(reshaped_matrix)


Array 1: [1 2 3 4]
Array 2: [5 6 7 8]

Horizontally Concatenated Array:
[1 2 3 4 5 6 7 8]

Vertically Concatenated Array:
[1 2 3 4 5 6 7 8]

Reshaped 2x4 Matrix:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np

# Generate a random 1D array with 100 elements
random_array = np.random.rand(100)

# Calculate the median of the array
median_value = np.median(random_array)

# Calculate the standard deviation of the array
std_deviation_value = np.std(random_array)

print("Random 1D Array:")
print(random_array)

print("\nMedian of the Array:", median_value)
print("Standard Deviation of the Array:", std_deviation_value)


Random 1D Array:
[0.27937649 0.44581432 0.00236825 0.0609117  0.92186456 0.05182757
 0.82735436 0.05106728 0.29648964 0.57629658 0.34421852 0.2256543
 0.68947829 0.72242092 0.52296597 0.93621017 0.98918846 0.89260559
 0.96022296 0.35732843 0.61706139 0.01173512 0.73761232 0.08639799
 0.35220345 0.15282045 0.62936786 0.60479291 0.70199408 0.10775366
 0.31003718 0.34240254 0.26177566 0.45789808 0.6828116  0.6610968
 0.23999715 0.27610004 0.50515393 0.67847396 0.14847461 0.36979512
 0.14518282 0.03276241 0.53459366 0.09049096 0.55812835 0.74608263
 0.5187512  0.41723737 0.27941691 0.11160328 0.30338283 0.45919434
 0.7481503  0.10146092 0.35936639 0.15950018 0.43751877 0.15034174
 0.11091403 0.41455258 0.90235342 0.80368295 0.07955881 0.00210209
 0.19104037 0.82337233 0.72486891 0.29202096 0.48814674 0.3261448
 0.09749178 0.07068618 0.55065393 0.76235428 0.24749395 0.41460306
 0.23776164 0.8309234  0.49169397 0.16676614 0.33323743 0.43337051
 0.8395315  0.65108945 0.56677093 0.39662268 0.4

In [ ]:
Create a 20 array with dimensione (3 4) and a 1D array with kength & be broadcasting to add the 10 array to each row of the 20 array

In [ ]:
import numpy as np

# Create a 2D array with dimensions (3, 4)
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Create a 1D array with length 4
array_1d = np.array([10, 10, 10, 10])

# Use broadcasting to add the 1D array to each row of the 2D array
result_array = array_2d + array_1d

print("Original 2D Array:")
print(array_2d)

print("\n1D Array to be Added:")
print(array_1d)

print("\nResult Array after Broadcasting:")
print(result_array)


Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1D Array to be Added:
[10 10 10 10]

Result Array after Broadcasting:
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [ ]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perform matrix multiplication using np.dot()
result_matrix = np.dot(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult of Matrix Multiplication (A * B):")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication (A * B):
[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np

# Create a NumPy array with random integers between 1 and 20
random_array = np.random.randint(1, 21, size=10)

# Use boolean indexing to extract elements greater than 10
result_array = random_array[random_array > 10]

print("Original Array:")
print(random_array)

print("\nElements Greater Than 10:")
print(result_array)


Original Array:
[17  4 18  2 13  1  4 16  7  7]

Elements Greater Than 10:
[17 18 13 16]


In [ ]:
import numpy as np

# Create a NumPy array
original_array = np.random.randint(1, 101, size=(3, 4))

# Save the array to a text file
np.savetxt('my_array.txt', original_array, fmt='%d')

# Load the array back from the text file
loaded_array = np.loadtxt('my_array.txt', dtype=int)

print("Original Array:")
print(original_array)

print("\nLoaded Array:")
print(loaded_array)

# Verify if the loaded array is the same as the original array
arrays_equal = np.array_equal(original_array, loaded_array)

print("\nAre the arrays equal?", arrays_equal)



Original Array:
[[68 71 72 10]
 [36 18 74 95]
 [98 65 10 87]]

Loaded Array:
[[68 71 72 10]
 [36 18 74 95]
 [98 65 10 87]]

Are the arrays equal? True


In [ ]:
import numpy as np

# Create an array of angles in radians
angles_radians = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])

# Calculate the sine of each angle
sine_values = np.sin(angles_radians)

# Create another array
original_array = np.array([1, 2, 3, 4, 5])

# Calculate the exponential of each element in the array
exp_values = np.exp(original_array)

print("Array of Angles in Radians:")
print(angles_radians)

print("\nSine Values:")
print(sine_values)

print("\nOriginal Array:")
print(original_array)

print("\nExponential Values:")
print(exp_values)


Array of Angles in Radians:
[0.         1.57079633 3.14159265 4.71238898 6.28318531]

Sine Values:
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]

Original Array:
[1 2 3 4 5]

Exponential Values:
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [ ]:
import numpy as np
import timeit

# Function to add lists element-wise
def add_lists_elementwise(list1, list2):
    return [x + y for x, y in zip(list1, list2)]

# Vectorized function using NumPy
vectorized_add = np.vectorize(lambda x, y: x + y)

# Generate two large lists
list_size = 10**6
list1 = np.random.rand(list_size).tolist()
list2 = np.random.rand(list_size).tolist()

# Measure the execution time for the pure Python function
time_python = timeit.timeit(lambda: add_lists_elementwise(list1, list2), number=1)

# Convert lists to NumPy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure the execution time for the vectorized NumPy function
time_numpy = timeit.timeit(lambda: vectorized_add(array1, array2), number=1)

print("Execution time for Python function:", time_python)
print("Execution time for NumPy vectorized function:", time_numpy)


Execution time for Python function: 0.16307380200009902
Execution time for NumPy vectorized function: 0.4260388860000148
